name: "Kafka-with-KRaft"

services: 
    kafka:
      image: bitnamilegacy/kafka:4.0.0-debian-12-r10
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
        - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
        - KAFKA_CFG_LOG_RETENTION_HOURS=168
        - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824
      volumes:
        - kafka_data:/var/lib/kafka/data

volumes:
  kafka_data: